### ISSUE TITLE
请问下,为什么不更新了

### ISSUE THREAD

**Issue by zyqf** [RyotaMono/SSnodePanel#1]
请问下,为什么不更新了

**Comment by RyotaMono** [comment]
SSnodePanel was a project forked from [ss-panel by orvice](https://github.com/orvice/ss-panel), and  was created for testing and debugging. You may fork [ss-panel by orvice](https://github.com/orvice/ss-panel) to get the latest update. Sorry for any inconveniences. 

SSnodePnael仅是[ss-panel by orvice](https://github.com/orvice/ss-panel)的一份拷贝，被用来进行测试和排错。您可以fork [ss-panel by orvice](https://github.com/orvice/ss-panel)来获取原作者的最新更新。对带来的不便深表歉意。
